name: MyChunk
main: me.ellbristow.mychunk.MyChunk
version: 2.0.5
author: ellbristow
description: >
             Buy/Sell chunks for currency, get protection, make profit.
softdepend: [Vault,My Worlds,Multiverse]

commands:
  mychunk:
    description: Main (and only) command

permissions:

# Admin Permissions
  mychunk.*:
    description: Admin permission for total access
    default: op
    children:
      mychunk.buy: true
      mychunk.commands.*: true
      mychunk.claim.*: true
      mychunk.free: true
      mychunk.override: true
      mychunk.sell: true
      mychunk.server.*: true
      mychunk.unclaim.*: true
      mychunk.allowmobs: true
  
  mychunk.free:
    description: Player does not pay to claim chunks
    default: op
  
  mychunk.override:
    description: Player can bypass chunk protections (handle with care!)
    default: op

# Command Permissions
  mychunk.commands.*:
    description: Access to all MyChunk commands
    default: op
    children:
      mychunk.commands.stats: true
      mychunk.commands.price: true
      mychunk.commands.obprice: true
      mychunk.commands.max: true
      mychunk.commands.flags: true
      mychunk.commands.expirydays: true
      mychunk.commands.toggle.*: true
      mychunk.commands.purge.*: true
      mychunk.commands.reload: true
  mychunk.commands.price:
    description: Access to command /mychunk price
    default: op
  mychunk.commands.obprice:
    description: Access to command /mychunk obprice
    default: op
  mychunk.commands.max:
    description: Access to command /mychunk max
    default: op
  mychunk.commands.expirydays:
    description: Access to command /mychunk expirydays
    default: op
  mychunk.commands.stats:
    description: Access to command /mychunk
    default: op
  mychunk.commands.flags:
    description: Access to command /mychunk flags
    default: op
  mychunk.commands.toggle.*:
    description: Access to all commands starting with /mychunk toggle
    default: op
    children:
      mychunk.commands.toggle.refund: true
      mychunk.commands.toggle.overbuy: true
      mychunk.commands.toggle.resales: true
      mychunk.commands.toggle.neighbours: true
      mychunk.commands.toggle.unclaimed: true
      mychunk.commands.toggle.tnt: true
      mychunk.commands.toggle.expiry: true
      mychunk.commands.toggle.allownether: true
      mychunk.commands.toggle.allowend: true
  mychunk.commands.toggle.refund:
    description: Access to command /mychunk toggle refund
    default: op
  mychunk.commands.toggle.overbuy:
    description: Access to command /mychunk toggle overbuy
    default: op
  mychunk.commands.toggle.resales:
    description: Access to command /mychunk toggle resales
    default: op
  mychunk.commands.toggle.neighbours:
    description: Access to command /mychunk toggle neighbours
    default: op
  mychunk.commands.toggle.unclaimed:
    description: Access to command /mychunk toggle unclaimed
    default: op
  mychunk.commands.toggle.tnt:
    description: Access to command /mychunk toggle tnt
    default: op
  mychunk.commands.toggle.expiry:
    description: Access to command /mychunk toggle expiry
    default: op
  mychunk.commands.toggle.allownether:
    description: Access to command /mychunk toggle allownether
    default: op
  mychunk.commands.toggle.allowend:
    description: Access to command /mychunk toggle allowend
    default: op
  mychunk.commands.purge.*:
    description: Access to all /muchunk purgep and /mychunk purgew
    default: op
    children:
      mychunk.commands.purgep: true
      mychunk.commands.purgew: true
  mychunk.commands.purgep:
    description: Access to /mychunk purgep
  mychunk.commands.purgew:
    description: Access to /mychunk purgew
  mychunk.commands.reload:
    description: Access to /mychunk reload

# Claim Permissions
  mychunk.claim.*:
    description: Can claim chunks for self/server/others
    default: op
    children:
       mychunk.claim: true
       mychunk.claim.others: true
       mychunk.claim.server: true
       mychunk.claim.unlimited: true
       mychunk.claim.others.unlimited: true
       mychunk.claim.overbuy: true
       mychunk.claim.area: true
  mychunk.claim:
    description: Can claim chunks
    default: op
  mychunk.claim.unlimited:
    description: Can ignore max chunk limit when claiming for self
    default: op
  mychunk.claim.others:
    description: Can claim chunks for other players
    default: op
  mychunk.claim.others.unlimited:
    description: Can ignore max chunk limit when claiming for others
    default: op
  mychunk.claim.server:
    description: Can claim chunks for the server
    default: op
  mychunk.claim.overbuy:
    description: Can buy more than the max limit for the overbuy price
    default: op
  mychunk.claim.area:
    description: Can buy chunks usign [ClaimArea] signs
    default: op

# Resale Permissions

  mychunk.sell:
    description: Can sell chunks with a [For Sale] sign
    default: op
  mychunk.buy:
    description: Can buy chunks set as [For Sale]
    default: op

# Server Permissions
  mychunk.server.*:
    description: Can build/destroy/use in server owned chunks.
    default: false
    children:
      mychunk.server.build: true
      mychunk.server.chests: true
      mychunk.server.destroy: true
      mychunk.server.doors: true
      mychunk.server.ignite: true
      mychunk.server.use: true
      mychunk.server.special: true
      mychunk.server.signs: true
  mychunk.server.build:
    description: Can build in server owned chunks
    default: op
  mychunk.server.chests:
    description: Can open chests in server owned chunks
    default: op
  mychunk.server.destroy:
    description: Can destroy blocks in server owned chunks
    default: op
  mychunk.server.doors:
    description: Can open doors in server owned chunks
    default: op
  mychunk.server.ignite:
    description: Can use explosives and Flint & Steel in server owned chunks
    default: op
  mychunk.server.use:
    description: Can use levers, buttons etc in server owned chunks
    default: op
  mychunk.server.special:
    description: Can access furnaces, dispensers and brewing stands in server owned chunks
    default: op
  mychunk.server.signs:
    description: Can use [Allow], [For Sale] etc in Server Chunks
    default: op

# Unclaim Permissions
  mychunk.unclaim.*:
    description: Can unclaim chunks for others/server
    default: op
    children:
      mychunk.unclaim.others: true
      mychunk.unclaim.server: true
  mychunk.unclaim.others:
    description: Can unclaim chunks for other players
    default: op
  mychunk.unclaim.server:
    description: Can unclaim chunks for other players
    default: op

# Speical Sign Permissions
  mychunk.allowmobs:
    description: Can use [AllowMobs] signs
    default: op
